version: '3.8'

services:
  app:
    build:
      context: .
    image: rust:1-alpine
    volumes:
      - ".:/app"
    env_file:
      - .env
    working_dir: /app
    command: [
      "cargo", "run", "--release"
    ]